/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matherapie;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class connexion extends javax.swing.JFrame {

    /**
     * Creates new form connexion
     */
    public connexion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        logintxt = new javax.swing.JTextField();
        nomtxt = new javax.swing.JTextField();
        prenomtxt = new javax.swing.JTextField();
        hommerb = new javax.swing.JRadioButton();
        femmerb = new javax.swing.JRadioButton();
        poidstxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        adressetxt = new javax.swing.JTextArea();
        teltxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        retourbtn = new javax.swing.JButton();
        reinitialiserbtn = new javax.swing.JButton();
        confirmerbtn = new javax.swing.JButton();
        loginlbl = new javax.swing.JLabel();
        mdplbl = new javax.swing.JLabel();
        nomlbl = new javax.swing.JLabel();
        prenomlbl = new javax.swing.JLabel();
        sexelbl = new javax.swing.JLabel();
        datelbl = new javax.swing.JLabel();
        poidslbl = new javax.swing.JLabel();
        adresselbl = new javax.swing.JLabel();
        tellbl = new javax.swing.JLabel();
        emaillbl = new javax.swing.JLabel();
        mdptxt = new javax.swing.JPasswordField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(142, 200, 214));
        jLabel3.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Connexion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 190, 60));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel4.setText("Login : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 120, 40));
        jLabel4.getAccessibleContext().setAccessibleName("jLabel4");

        jTextField1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 370, 40));

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel5.setText("Mot de passe :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 190, 40));

        jButton1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton1.setText("Réinitialiser");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 180, 40));

        jButton2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jButton2.setText("S'identifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 160, 40));

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel6.setText("vous n'êtes pas encore inscrits ?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 280, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Cliquez-ici");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 130, -1));

        jPasswordField1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 370, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\icons\\medicRight.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 720));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\icons\\matherapie.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 640, 720));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel8.setText("Inscription");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 270, -1));

        logintxt.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jPanel3.add(logintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 250, 30));

        nomtxt.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jPanel3.add(nomtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 250, 30));
        jPanel3.add(prenomtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 250, 30));

        buttonGroup1.add(hommerb);
        hommerb.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        hommerb.setText("Homme");
        jPanel3.add(hommerb, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        buttonGroup1.add(femmerb);
        femmerb.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        femmerb.setText("Femme");
        jPanel3.add(femmerb, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));
        jPanel3.add(poidstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 250, 30));

        adressetxt.setColumns(20);
        adressetxt.setRows(5);
        jScrollPane1.setViewportView(adressetxt);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 250, -1));
        jPanel3.add(teltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 250, 30));
        jPanel3.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 250, 30));

        retourbtn.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        retourbtn.setText("Retour");
        retourbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourbtnActionPerformed(evt);
            }
        });
        jPanel3.add(retourbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 640, 120, -1));

        reinitialiserbtn.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        reinitialiserbtn.setText("Reinitialiser");
        reinitialiserbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reinitialiserbtnActionPerformed(evt);
            }
        });
        jPanel3.add(reinitialiserbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, 140, -1));

        confirmerbtn.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        confirmerbtn.setText("Confirmer");
        confirmerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmerbtnActionPerformed(evt);
            }
        });
        jPanel3.add(confirmerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 640, 130, -1));

        loginlbl.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        loginlbl.setText("Login :");
        jPanel3.add(loginlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 140, 20));

        mdplbl.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        mdplbl.setText("Mot de passe :");
        jPanel3.add(mdplbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 114, 150, 30));

        nomlbl.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        nomlbl.setText("Nom :");
        jPanel3.add(nomlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 150, 30));

        prenomlbl.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        prenomlbl.setText("Prénom :");
        jPanel3.add(prenomlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 140, 30));

        sexelbl.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        sexelbl.setText("Sexe :");
        jPanel3.add(sexelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 130, 20));

        datelbl.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        datelbl.setText("Date de naissance :");
        jPanel3.add(datelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 200, -1));

        poidslbl.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        poidslbl.setText("Poids :");
        jPanel3.add(poidslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 140, 30));

        adresselbl.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        adresselbl.setText("Adresse :");
        jPanel3.add(adresselbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 150, 30));

        tellbl.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        tellbl.setText("Telephone :");
        jPanel3.add(tellbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 514, 120, 20));

        emaillbl.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        emaillbl.setText("Email :");
        jPanel3.add(emaillbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 100, 20));
        jPanel3.add(mdptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 250, 30));
        jPanel3.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 250, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\icons\\medicRight.png")); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 720));
        jPanel3.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jTextField1.setText("");
jPasswordField1.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
jPanel1.setVisible(false);
jPanel3.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void reinitialiserbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinitialiserbtnActionPerformed
logintxt.setText(""); 
nomtxt.setText("");
prenomtxt.setText("");
buttonGroup1.clearSelection();
poidstxt.setText("");
adressetxt.setText("");
teltxt.setText("");
emailtxt.setText("");
mdptxt.setText("");
jDateChooser1.setCalendar(null);
// TODO add your handling code here:
    }//GEN-LAST:event_reinitialiserbtnActionPerformed

    private void retourbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourbtnActionPerformed
jPanel1.setVisible(true);
jPanel3.setVisible(false);      // TODO add your handling code here:
    }//GEN-LAST:event_retourbtnActionPerformed

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
if(evt.getKeyCode() == 10) {
				jButton2.doClick();
			}        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Utilisateur user = new Utilisateur(jTextField1.getText().toLowerCase(), jPasswordField1.getText());
if(user.seConnecter()) {
                    index i = new index();
                i.setVisible(true);
    connexion.this.dispose();
	       // TODO add your handling code here:
            }   
else {
				JOptionPane.showMessageDialog(null, "Login et/ou mot de passe incorrect(s)", "Erreur",
						JOptionPane.ERROR_MESSAGE);
			}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void confirmerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmerbtnActionPerformed
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(jDateChooser1.getDate());
        Utilisateur user = new Utilisateur(logintxt.getText(), mdptxt.getText(), nomtxt.getText(), prenomtxt.getText(), String.valueOf(buttonGroup1.getSelection().getActionCommand()), date, Float.parseFloat(poidstxt.getText()), adressetxt.getText(), teltxt.getText(), emailtxt.getText()); 
        if(user.sInscrire()) {
					JOptionPane.showConfirmDialog(null, "Cliquez sur OK pour continuer ...", "Inscription réussie !", JOptionPane.DEFAULT_OPTION);
					connexion c = new connexion();
					c.setVisible(true);
					connexion.this.dispose();
				} else {
					
				}
// TODO add your handling code here:
    }//GEN-LAST:event_confirmerbtnActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new connexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adresselbl;
    private javax.swing.JTextArea adressetxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton confirmerbtn;
    private javax.swing.JLabel datelbl;
    private javax.swing.JLabel emaillbl;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JRadioButton femmerb;
    private javax.swing.JRadioButton hommerb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel loginlbl;
    private javax.swing.JTextField logintxt;
    private javax.swing.JLabel mdplbl;
    private javax.swing.JPasswordField mdptxt;
    private javax.swing.JLabel nomlbl;
    private javax.swing.JTextField nomtxt;
    private javax.swing.JLabel poidslbl;
    private javax.swing.JTextField poidstxt;
    private javax.swing.JLabel prenomlbl;
    private javax.swing.JTextField prenomtxt;
    private javax.swing.JButton reinitialiserbtn;
    private javax.swing.JButton retourbtn;
    private javax.swing.JLabel sexelbl;
    private javax.swing.JLabel tellbl;
    private javax.swing.JTextField teltxt;
    // End of variables declaration//GEN-END:variables
}
